{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-service.fullname" . }}-configmap
  labels:
    {{- include "app-service.labels" . | nindent 4 }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
