apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-service.fullname" . }}
  labels:
    {{- include "app-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy: 
    type: {{ .Values.strategy.type | default "RollingUpdate" | quote }}
  selector:
    matchLabels:
      {{- include "app-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:   
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}    
      {{- end }}
      labels:
        {{- include "app-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "app-service.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env: 
          ports:
            - name: {{ printf "http-%s-pod-port" (include "app-service.fullname" .) | trunc 15 | trimSuffix "-" }}
              containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ tpl .Values.containers.probePath . }}
              port: {{ .Values.containers.ports.containerPort }}
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: {{ tpl .Values.containers.probePath . }}
              port: {{ .Values.containers.ports.containerPort }}
            periodSeconds: 10
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: {{ tpl .Values.containers.probePath . }}
              port: {{ .Values.containers.ports.containerPort }}
            periodSeconds: 5
            failureThreshold: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
