name: Continuous integration

on:
  push:
    branches:
      - main


jobs:
  cicd:
    name: CI CD
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws_account_id: "499490329151"
      region: ap-east-1
      project_name: demo-project-ecr-dev

    steps:
      - name: Check out app repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        # Override language selection by uncommenting this and choosing your languages
        with:
          languages: javascript

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - name: Build Image
        if: always()
        run: |-
          echo $GITHUB_SHA
          docker login -u AWS -p $(aws ecr get-login-password --region ${{ env.region }}) ${{ env.aws_account_id }}.dkr.ecr.${{ env.region }}.amazonaws.com

          docker build -f ./Dockerfile \
            --tag "${{ env.aws_account_id }}.dkr.ecr.${{ env.region }}.amazonaws.com/${{ env.project_name }}:$GITHUB_SHA" \
            ./

          docker push "${{ env.aws_account_id }}.dkr.ecr.${{ env.region }}.amazonaws.com/${{ env.project_name }}:$GITHUB_SHA"
        shell: bash






